export interface Goods {
  advState?: number
  afterSalesRate?: number
  agentMedia?: AgentMedia
  applauseRate?: number
  bigTuanJiaCha?: number
  bookingNum?: number
  bossReward?: number
  buyerCommentTips?: string
  cancelOrder?: number
  captainId?: number
  costPrice?: number
  currentPayPrice?: number
  deliveryRemark?: string
  earnings?: number
  endTime?: string
  fareId?: number
  goodsCatId?: number
  goodsCdate?: string
  goodsId?: number
  goodsImgId?: number
  goodsImgLongUrl?: string
  goodsSmallPiecesNum?: number
  goodsStatus?: number
  goodsTag?: string
  goodsTitle?: string
  goodsUdate?: string
  hasRewardRemind?: boolean
  introduction?: string
  leaderRewardStatus?: number
  level1Commission?: number
  level2Commission?: number
  mallType?: number
  newAgentFlag?: number
  orderLimit?: number
  orderLimitMin?: number
  orderLimitTotal?: number
  platformDeliveryTime?: number
  price?: number
  priceOrigin?: number
  prime1Price?: number
  prime2Price?: number
  prime3Price?: number
  priorityNo?: number
  question?: string
  recommendReason?: string
  remark?: string
  rewardReminderStatus?: number
  salesNum?: number
  salesNumYesterday?: number
  selectStatus?: number
  selectStatusCdate?: string
  selectedRecommendNum?: number
  sellingPoints?: string
  shareProfit?: number
  shareSwitch?: number
  skuLimit?: number
  startTime?: string
  stock?: number
  stopSellComment?: string
  superLevel1Commission?: number
  superLevel2Commission?: number
  superTuanJiaCha?: number
  supplierDeliveryTime?: number
  supplierGoodsName?: string
  supplierId?: number
  supplierRemark?: string
  tag?: string
  teamRewardStatus?: number
  topStatus?: number
  unitName?: string
  virtualSalesNum?: number
  virtualStock?: number
  vonderFareId?: number
  warehouse?: string
}

interface AgentMedia {
  agentMediaId: number
  downloadDate: string
  downloadStatus: number
  entityId: number
  mediaCdate: string
  mediaType: number
  mediaUrl: string
  storeType: number
}
