// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import("@arco-design/web-vue")["Button"]
    ASpace: typeof import('@arco-design/web-vue')['Space']
    BackButton: typeof import('./components/Layout/components/layout-header/BackButton.vue')['default']
    Header: typeof import("./components/Layout/components/header/index.vue")["default"]
    Layout: typeof import('./components/Layout/index.vue')['default']
    LayoutHeader: typeof import('./components/Layout/components/layout-header/index.vue')['default']
    Logo: typeof import('./components/Layout/components/layout-header/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
  }
}
