// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    AImage: typeof import('@arco-design/web-vue')['Image']
    AInputSearch: typeof import('@arco-design/web-vue')['InputSearch']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    AProgress: typeof import('@arco-design/web-vue')['Progress']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    BackButton: typeof import('./components/Layout/components/layout-header/BackButton.vue')['default']
    HeaderTabs: typeof import('./components/Layout/components/layout-header/HeaderTabs.vue')['default']
    Iconfont: typeof import('./components/Iconfont/index.vue')['default']
    IconPark: typeof import('./components/IconPark/index.vue')['default']
    Layout: typeof import('./components/Layout/index.vue')['default']
    LayoutFooter: typeof import('./components/Layout/components/layout-footer/index.vue')['default']
    LayoutHeader: typeof import('./components/Layout/components/layout-header/index.vue')['default']
    LayoutSider: typeof import('./components/Layout/components/layout-sider/index.vue')['default']
    Login: typeof import('./components/Layout/components/layout-sider/Login.vue')['default']
    LoginDialog: typeof import('./components/loginDialog/index.vue')['default']
    Logo: typeof import('./components/Layout/components/layout-header/Logo.vue')['default']
    MusicTabs: typeof import('./components/MusicTabs/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Layout/components/layout-header/search.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    TableTabs: typeof import('./components/Layout/components/layout-header/TableTabs.vue')['default']
    Tools: typeof import('./components/Layout/components/layout-header/tools.vue')['default']
  }
}
